---
  - name: upload ssh keys
    copy: src=~/.ssh/{{ item }} dest=~/.ssh/ owner=root group=root mode=0600
    become: yes
    with_items:
      - ansible_deploy
      - ansible_deploy.pub
    tags:
      - git_clone_repo

  - name: clone birdmagaja repository
    git: repo="git@bitbucket.org:operacioncoconut/warehouse-whitemirlo.git"
         clone=yes
         dest="/home/develop/warehouse-whitemirlo/"
         accept_hostkey=yes
         key_file="~/.ssh/ansible_deploy"
    become: yes
    tags:
      - git-clone-repo

  - name: copy files to develop root
    command: chdir=/home/develop/ cp -r warehouse-whitemirlo/{{ item }} .
    with_items:
      - birdmagaja
      - genalmacen.sh
    become: yes
    tags:
      - git-clone-repo

  - name: execute genalmacen.sh
    command: chdir=/home/develop/ creates=almacen /bin/bash genalmacen.sh
    become: yes
    tags:
      - git-clone-repo

  - name: ensure almacen folder is owned by www-data
    file: path=/home/develop/almacen owner=www-data group=www-data mode=0744 state=directory recurse=yes
    become: yes
    tags:
      - git-clone-repo

  - name: install requirements
    pip: chdir=/home/develop/birdmagaja requirements=requirements.txt state=present virtualenv=/home/develop/.virtualenvs/birdmagaja
    become: yes
    tags:
      - git-clone-repo

  - name: create encryption file
    lineinfile: create=yes dest=/home/develop/secret/iv insertbefore=BOF line="sdsddasdsa" owner=root group=root mode=0644
    become: yes
    tags:
      - git-clone-repo

  - name: upload local_settings.py
    template: src=master_local_settings.j2 dest=/home/develop/birdmagaja/birdmagaja/local_settings.py owner=root group=root mode=0644
    become: yes
    tags:
      - upload-local-settings