---
- hosts: all
  vars_files:
    - /home/flopez/ansible/host_vars/passwords/{{inventory_hostname}}
  tasks:
  - name: install packages
    sudo: yes
    apt: state=latest pkg={{ item }} update_cache=yes
    with_items:
      - nagios-nrpe-server
      - nagios-plugins
    tags:
      - packages

  - name: upload check_mem
    sudo: yes
    copy: src=checks/check_mem.pl dest=/usr/lib/nagios/plugins/ owner=root group=root mode=0755
    tags:
      - config

  - name: copy over base NRPE config file
    sudo: yes
    template: src=templates/nrpe.cfg dest=/etc/nagios/ owner=root group=root mode=0644
    tags:
      - config

  - name: copy over base commands file
    sudo: yes
    template: src=templates/base_commands.cfg dest=/etc/nagios/nrpe.d owner=root group=root mode=0644
    tags:
      - config

  - name: find out if a specific configuration file exists
    local_action: stat path=templates/specific/{{ inventory_hostname }}.cfg
    register: specific_conf
    tags:
      -configure

  - name: copy over specific configuration file
    sudo: yes
    template: src=specific/{{ inventory_hostname }}.cfg dest=/etc/nagios/nrpe.d/{{ inventory_hostname }}.cfg owner=root group=root mode=0644
    when: specific_conf.stat.exists
    tags:
      - config

  - name: restart nagios-nrpe-server
    sudo: yes
    service: name=nagios-nrpe-server state=restarted
    when: specific_conf.stat.exists
    tags:
     - config
