---
  - name: add bitbucket.org to ssh known hosts
    lineinfile: >
      dest=/etc/ssh/ssh_known_hosts
      state=present
      create=true
      owner=root
      group=root
      mode=0644
      line='{{ git.host_keys.bitbucket_org }}'
    become: yes
    tags:
      - git_clone_repo

  - name: upload ssh keys
    copy: src=~/.ssh/{{ item }} dest=~/.ssh/ owner=root group=root mode=0600
    become: yes
    with_items:
      - ansible_deploy
      - ansible_deploy.pub
    tags:
      - git_clone_repo

  - name: clone birdmagaja repository
    git: repo="git@bitbucket.org:operacioncoconut/gta.git"
         clone=yes
         dest="/home/develop/gta/"
         accept_hostkey=yes
         key_file="~/.ssh/ansible_deploy"
    become: yes
    tags:
      - git_clone_repo
