---
   -  name: install python packages
      apt: name={{item}} state=present
      sudo: yes
      with_items:
         -  python
         -  python-pip
         -  python-dev
      tags: 
         - python
         - install_python