---
- name: install packages
  sudo: yes
  apt: state=present pkg={{ item }} update_cache=yes
  with_items:
    - nagios-nrpe-server
    - nagios-plugins
  tags:
    - packages

- name: upload check_mem
  sudo: yes
  copy: src=checks/check_mem.pl dest=/usr/lib/nagios/plugins/ owner=root group=root mode=0755
  tags:
    - config

- name: copy over NRPE config file
  sudo: yes
  template: src=nagios-client/nrpe.cfg dest=/etc/nagios/ owner=root group=root mode=0644
  tags:
    - config

# - name: copy over base commands file
#   sudo: yes
#   template: src=nagios-client/base-commands.cfg dest=/etc/nagios/nrpe.d/ owner=root group=root mode=0644
#   tags:
#     - config

# - name: find out if a specific configuration file exists
#   local_action: stat path=templates/nagios-client/specific/{{ ansible_hostname }}.cfg
#   register: specific_conf
#   tags:
#     -config

# - name: copy over specific configuration file
#   sudo: yes
#   template: src=specific/{{ ansible_hostname }}.cfg dest=/etc/nagios/nrpe.d/{{ ansible_hostname }}.cfg owner=root group=root mode=0644
#   when: specific_conf.stat.exists != False
#   tags:
#      - config

#- include: nagios_server.yml
