---
-hosts: eris

  - name: upload base configuration for each server
    sudo: yes
    template: src=server/{{ ansible_hostname }}.cfg dest=/etc/nagios/ owner=root group=root mode=0644

  - name: install packages
    sudo: yes
    apt: state=latest pkg={{ item }} update_cache=yes
    with_items:
      - nagios-nrpe-server
      - nagios-plugins
    tags:
      - packages
  
  - name: upload check_mem
    sudo: yes
    copy: src=checks/check_mem.pl dest=/usr/lib/nagios/plugins/ owner=root group=root mode=0755
    tags:
      - config
  
  - name: copy over base NRPE checks config file
    sudo: yes
    template: src=nrpe.cfg dest=/etc/nagios/ owner=root group=root mode=0644
    tags:
      - config
  
  - name: find out if a specific configuration file exists
    local_action: stat path=templates/specific/{{ ansible_hostname }}.cfg
    register: specific_conf_exists
    tags:
      -config
  
  - name: copy over specific configuration file
    sudo: yes
    template: src=specific/{{ ansible_hostname }}.cfg dest=/etc/nagios/nrpe.d/{{ ansible_hostname }}.cfg owner=root group=root mode=0644
    when: specific_conf_exists|success
    tags:
      - config
  
  - name: copy over standard nrpe config
    sudo: yes
    template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
    notify:
      - restart nrpe
    tags:
      - config
  