---
  - name: Is MySQL installed?
    become: yes
    apt: name="mysql-server" state=present update_cache=yes
    tag:
      - mysql
      - mysql-install

  - name: Install playbook dependencies
    apt: name="python-mysqldb" state=present 
    tag:
      - mysql
      - mysql-install

  - name: Change root password
    mysql_user: name=root password={{ mysql_root_pass }}

  - name: Drop ~/.my.cnf file
    template: src=my.cnf dst=/root/.my.cnf


  # - include: bootstrap.yml
  #   when: mysql-installed|failed


