---
    - name: Is php present?
      yum:  name=php state=present
      register: php_is_present
      sudo: yes

    - name: Install the latest php package
      yum:  name=php state=latest
      sudo: yes
      when: php_is_present|failed