---

  - name: installing monitoring packages
    sudo: yes
    apt: state=latest pkg={{ item }} update_cache=yes
    with_items:
      - nagios-nrpe-server
      - nagios-plugins
    tags:
      - monitoring
      - packages

  - name: upload check_mem.pl
    sudo: yes
    copy: src=nagios/checks/check_mem.pl dest=/usr/lib/nagios/plugins/ owner=root group=root mode=0755
    tags:
      - monitoring
      - config

  - name: upload nrpe.cfg 
    sudo: yes
    template: src=monitoring/nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
    notify:
      - restart nrpe
    tags:
      - monitoring
      - config

  - name: upload base.cfg file for basic checks
    sudo: yes
    template: src=monitoring/base.cfg dest=/etc/nagios/nrpe.d/base.cfg owner=root group=root mode=0644
    tags:
      - config
      - monitoring

  - name: check for host specific configuration
    local_action: "stat path=templates/monitoring/{{ ansible_hostname }}.cfg"
    sudo: no
    register: host_conf
    tags:
      - config
      - monitoring
      - host_config

  - name: upload specific configuration file
    sudo: yes
    template: src=templates/monitoring/{{ ansible_hostname }}.cfg dest=/etc/nagios/nrpe.d/{{ ansible_hostname }}.cfg owner=root group=root mode=0644
    when: host_conf.stat.exists == True
    tags:
      - config
      - monitoring
      - host_config


