
- hosts: sana5
  vars_files:
    #- /home/flopez/ansible/host_vars/passwords/{{inventory_hostname}}
    #- /home/flopez/ansible/host_vars/{{inventory_hostname}}
  tasks:
    - name: Create dvaca user 
      user: name=dvaca comment="Daniel Vaca" shell=/bin/bash  groups=sudo update_password=on_create state=present 


    - name: Create framirez user 
      user: name=framirez comment="Fernando Ramirez" shell=/bin/bash  groups=sudo update_password=on_create state=present 


    - name: Create backuo user 
      user: name=backuo comment="Backuo McBack" shell=/bin/bash  update_password=on_create state=present 
