---
- hosts: physical

  vars_files:
      #- /home/flopez/ansible_playbooks/vars/passwords.yml
      - /home/flopez/ansible/host_vars/passwords/{{inventory_hostname}}

  vars:
      #ansible_sudo_pass: "{{ lookup('file', '/home/flopez/ansible_playbooks/host_vars/passwords/' + inventory_hostname) }}"
      # with_password: "{{ lookup('password', '/home/flopez/ansible_playbooks/host_vars/passwords/' + inventory_hostname) }}"  

  tasks:   

    - name: update apt
      apt: update_cache=yes
      sudo: yes

    - name: update glibc
      apt: name=libc6 state=latest
      sudo: yes